apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::982534393200:role/eksctl-simple-jwt-api-nodegroup-si-NodeInstanceRole-xgPZj2OIQBNO
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::982534393200:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2025-01-11T23:11:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1411"
  uid: 1d36d3cf-59bf-43ed-9c73-8273ed8d7242
